### ISSUE TITLE
Does this tool work with other games?

### ISSUE THREAD

**Issue by biokhufu** [Illidanz/ShitoTranslation#1]
Hello, I want to translate some other ws games, can I use this tool? If so, what do I need to modify before it can be used?

**Comment by Illidanz** [comment]
Not likely, every game is probably going to be substantially different.

You can find some general-purpose code here https://github.com/Illidanz/wsdisasm and here https://github.com/Illidanz/hacktools/blob/master/hacktools/ws.py
